spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://pgsql01-to-make-sure-tests-dont-use-this-url:5432/xchange?currentSchema=calisma
    username: admin
    password: simon
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
  init:
    mode: always
